# This is a config for E2B sandbox template.
# You can use template ID (qus5p5na0bdzzc0v6uvg) or template name (vibe-land-nextjs) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-land-nextjs") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-land-nextjs") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-land-nextjs')

team_id = "1efe4e58-7dcb-45d4-8b09-00983ac07464"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-land-nextjs"
template_id = "qus5p5na0bdzzc0v6uvg"
